In [2]:
import pandas as pd

In [3]:
data=pd.read_csv("pokemon.csv")

In [4]:
data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [5]:
data.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   Total       800 non-null    int64
 5   HP          800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int64
 12  Legendary   800 non-null    bool
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB

In [9]:
data.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [11]:
data["Type 1"].value_counts

Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Rock         44
Electric     44
Ground       32
Dragon       32
Ghost        32
Dark         31
Poison       28
Fighting     27
Steel        27
Ice          24
Fairy        17
Flying        4
Name: Type 1, dtype: int64

In [14]:
data.sort_values("Defense",ascending=False)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False
224,208,SteelixMega Steelix,Steel,Ground,610,75,125,230,55,95,30,2,False
333,306,AggronMega Aggron,Steel,NaN,630,70,140,230,60,80,50,3,False
223,208,Steelix,Steel,Ground,510,75,85,200,55,65,30,2,False
414,377,Regirock,Rock,NaN,580,80,100,200,50,100,50,3,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,63,Abra,Psychic,NaN,310,25,20,15,105,55,90,1,False
186,172,Pichu,Electric,NaN,205,20,40,15,35,35,60,2,False
261,242,Blissey,Normal,NaN,540,255,10,10,75,135,55,2,False
488,440,Happiny,Normal,NaN,220,100,5,5,15,65,30,4,False
121,113,Chansey,Normal,NaN,450,250,5,5,35,105,50,1,False

In [16]:
data.sort_values("Defense")

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
121,113,Chansey,Normal,NaN,450,250,5,5,35,105,50,1,False
488,440,Happiny,Normal,NaN,220,100,5,5,15,65,30,4,False
261,242,Blissey,Normal,NaN,540,255,10,10,75,135,55,2,False
186,172,Pichu,Electric,NaN,205,20,40,15,35,35,60,2,False
188,174,Igglybuff,Normal,Fairy,210,90,30,15,40,20,15,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
414,377,Regirock,Rock,NaN,580,80,100,200,50,100,50,3,True
223,208,Steelix,Steel,Ground,510,75,85,200,55,65,30,2,False
333,306,AggronMega Aggron,Steel,NaN,630,70,140,230,60,80,50,3,False
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False
224,208,SteelixMega Steelix,Steel,Ground,610,75,125,230,55,95,30,2,False

In [19]:
data.sort_values(["HP","Defense"],ascending=[True,False])

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
316,292,Shedinja,Bug,Ghost,236,1,90,45,30,30,40,3,False
55,50,Diglett,Ground,NaN,265,10,55,25,35,45,95,1,False
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False
388,355,Duskull,Ghost,NaN,295,20,40,90,30,90,25,3,False
139,129,Magikarp,Water,NaN,200,20,10,55,15,20,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,594,Alomomola,Water,NaN,470,165,75,80,40,45,65,5,False
351,321,Wailord,Water,NaN,500,170,90,45,90,45,60,3,False
217,202,Wobbuffet,Psychic,NaN,405,190,33,58,33,58,33,2,False
121,113,Chansey,Normal,NaN,450,250,5,5,35,105,50,1,False
261,242,Blissey,Normal,NaN,540,255,10,10,75,135,55,2,False

In [28]:
attack_mean=data["Attack"].mean()

def set_attack(val):
    if val< attack_mean:
        return "Attack Low"
    elif val==attack_mean:
        return "Attack neutral"
    else:
        return "Attack High"

In [29]:
data["Attack_high_low"]=data["Attack"].apply(set_attack)
data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Attack_high_low
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Attack Low
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Attack Low
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,Attack High
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,Attack High
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Attack Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,Attack High
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,Attack High
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,Attack High
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,Attack High
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,Attack High

In [30]:
speed_mean=data["Speed"].mean()

def set_speed(val):
    if val< speed_mean:
        return "Speed Low"
    elif val==speed_mean:
        return "Speed neutral"
    else:
        return "Speed High"

In [31]:
data["Speed_high_low"]=data["Speed"].apply(set_speed)
data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Attack_high_low,Speed_high_low
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Attack Low,Speed Low
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Attack Low,Speed Low
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,Attack High,Speed High
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,Attack High,Speed High
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Attack Low,Speed Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,Attack High,Speed Low
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,Attack High,Speed High
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,Attack High,Speed High
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,Attack High,Speed High
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,Attack High,Speed High

In [32]:
hp_mean=data["HP"].mean()

def set_hp(val):
    if val< hp_mean:
        return "HP Low"
    elif val==hp_mean:
        return "HP neutral"
    else:
        return "HP High"

In [33]:
data["HP_high_low"]=data["HP"].apply(set_hp)
data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Attack_high_low,Speed_high_low,HP_high_low
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Attack Low,Speed Low,HP Low
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Attack Low,Speed Low,HP Low
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,Attack High,Speed High,HP High
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,Attack High,Speed High,HP High
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Attack Low,Speed Low,HP Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,Attack High,Speed Low,HP Low
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,Attack High,Speed High,HP Low
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,Attack High,Speed High,HP High
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,Attack High,Speed High,HP High
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,Attack High,Speed High,HP High